const EXTENSION_TO_MIME: Readonly<Record<string, string>> = {
  pdf: "application/pdf",
  doc: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  webp: "image/webp",
  gif: "image/gif",
  svg: "image/svg+xml",
  bmp: "image/bmp",
  tif: "image/tiff",
  tiff: "image/tiff",
  heic: "image/heic",
  heif: "image/heif",
  ico: "image/x-icon",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  xls: "application/vnd.ms-excel",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  ppt: "application/vnd.ms-powerpoint",
  txt: "text/plain",
  csv: "text/csv",
  json: "application/json",
  html: "text/html",
  htm: "text/html",
  rtf: "application/rtf",
  xml: "application/xml",
  mp4: "video/mp4",
  avi: "video/x-msvideo",
  webm: "video/webm",
  mov: "video/quicktime",
  mp3: "audio/mpeg",
  wav: "audio/wav",
  ogg: "audio/ogg",
  js: "application/javascript",
  jsx: "text/jsx",
  ts: "application/typescript",
  tsx: "text/tsx",
  py: "text/x-python",
  java: "text/x-java",
  md: "text/markdown",
  yml: "text/yaml",
  yaml: "text/yaml",
  css: "text/css",
  sql: "text/x-sql",
  sh: "application/x-sh",
};

export function inferMimeFromFileName(fileName: string): string | null {
  const bare = fileName.split(".").pop()?.toLowerCase();
  return bare ? (EXTENSION_TO_MIME[bare] ?? null) : null;
}
