const MIME_TO_LANGUAGE: Record<string, string> = {
  "text/javascript": "javascript",
  "application/javascript": "javascript",
  "application/x-javascript": "javascript",
  "text/typescript": "typescript",
  "application/typescript": "typescript",
  "text/jsx": "jsx",
  "text/tsx": "tsx",
  "text/x-python": "python",
  "application/x-python": "python",
  "text/x-java": "java",
  "application/java": "java",
  "text/x-java-source": "java",
  "text/html": "markup",
  "application/xml": "markup",
  "text/xml": "markup",
  "text/css": "css",
  "text/x-c": "c",
  "text/x-c++": "cpp",
  "text/x-csharp": "csharp",
  "application/json": "json",
  "text/json": "json",
  "application/yaml": "yaml",
  "text/yaml": "yaml",
  "text/x-yaml": "yaml",
  "text/markdown": "markdown",
  "text/x-markdown": "markdown",
  "text/x-ruby": "ruby",
  "application/x-ruby": "ruby",
  "text/x-php": "php",
  "application/x-php": "php",
  "text/x-go": "go",
  "text/x-rust": "rust",
  "text/x-swift": "swift",
  "text/x-kotlin": "kotlin",
  "text/x-sql": "sql",
  "application/sql": "sql",
  "text/x-sh": "bash",
  "application/x-sh": "bash",
  "application/x-bash": "bash",
  "text/plain": "plaintext",
};

const EXT_TO_LANGUAGE: Record<string, string> = {
  js: "javascript",
  jsx: "jsx",
  ts: "typescript",
  tsx: "tsx",
  py: "python",
  java: "java",
  html: "markup",
  htm: "markup",
  xml: "markup",
  css: "css",
  c: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  cs: "csharp",
  json: "json",
  yaml: "yml",
  yml: "yaml",
  md: "markdown",
  rb: "ruby",
  php: "php",
  go: "go",
  rs: "rust",
  swift: "swift",
  kt: "kotlin",
  kts: "kotlin",
  sql: "sql",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
};

export function getSourceLanguageFromFile(mimeType: string, fileName: string): string {
  const mime = mimeType?.toLowerCase() ?? "";
  const langFromMime = MIME_TO_LANGUAGE[mime];
  if (langFromMime) return langFromMime;

  const ext = fileName?.split(".").pop()?.toLowerCase() ?? "";
  return EXT_TO_LANGUAGE[ext] ?? "plaintext";
}
